name: ceu_course
channels:
  - defaults
dependencies:
  - bleach
  - colorama
  - cycler
  - decorator
  - entrypoints
  - graphviz
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - markupsafe
  - matplotlib
  - mistune
  - mkl
  - nbconvert
  - nbformat
  - networkx
  - notebook
  - numpy
  - pandas
  - pandocfilters
  - path.py
  - patsy
  - pickleshare
  - pip
  - plotly
  - prompt_toolkit
  - pydotplus
  - pygments
  - pyparsing
  - pyqt
  - python
  - python-dateutil
  - python-graphviz
  - pytz
  - pyzmq
  - qtconsole
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - simplegeneric
  - sip
  - six
  - statsmodels
  - testpath
  - tornado
  - traitlets
  - wcwidth
  - wheel
  - widgetsnbextension
  - pip:
    - jupyter-contrib-core
    - jupyter-contrib-nbextensions
    - jupyter-highlight-selected-word
    - jupyter-latex-envs
    - jupyter-nbextensions-configurator
    - ldap3
    - lxml
    - nbextensions
    - pyasn1
    - pyyaml

